# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Roku / Build sideload package

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  build-sideload-package:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Sideload Package
        run: make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: truex-raf-examples
          path: dist/apps/truex-raf-examples.zip
